# Generated by Django 4.2 on 2025-09-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.CharField(default='Рядовой', max_length=100, verbose_name='Звание'),
        ),
    ]
