# Generated by Django 4.2 on 2025-09-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, verbose_name='Имя пользователя')),
                ('login', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Логин')),
                ('password', models.CharField(editable=False, max_length=100, verbose_name='Пароль')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
    ]
